# shopify.app.toml
scopes = "read_orders,read_products,write_products,read_script_tags,write_script_tags,write_draft_orders"
application_url = "https://apps.krcustomizer.com"
embedded = true

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
topics = ["orders/create"]

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://apps.krcustomizer.com/api/webhooks"

[auth]
redirect_urls = [
  "https://apps.krcustomizer.com/api/auth/callback"
]