# shopify.app.toml
scopes = "read_orders,read_products,write_products,read_script_tags,write_script_tags,write_draft_orders"
application_url = "https://apps.krcustomizer.com"
embedded = true

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topic = "orders/create"
uri = "https://apps.krcustomizer.com/api/webhooks/orders"

# UPDATE THESE TO MATCH YOUR WORKING APP:
[[webhooks.subscriptions]]
topic = "customers/data_request"
uri = "https://apps.krcustomizer.com/api/gdpr/customers_data_request"

[[webhooks.subscriptions]]
topic = "customers/redact" 
uri = "https://apps.krcustomizer.com/api/gdpr/customers_redact"

[[webhooks.subscriptions]]
topic = "shop/redact"
uri = "https://apps.krcustomizer.com/api/gdpr/shop_redact"

[auth]
redirect_urls = [
  "https://apps.krcustomizer.com/api/auth/callback"
]