#shopify.app.toml
# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cc7ed34fdd23728e1172722cfdd631e5"
name = "KR Customizer"
application_url = "https://apps.krcustomizer.com"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,read_orders,read_products,write_products,read_script_tags,write_script_tags"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request"]
uri = "https://apps.krcustomizer.com/api/webhooks/customers/data_request"

[[webhooks.subscriptions]]
compliance_topics = ["customers/redact"]
uri = "https://apps.krcustomizer.com/api/webhooks/customers/redact"

[[webhooks.subscriptions]]
compliance_topics = ["shop/redact"]
uri = "https://apps.krcustomizer.com/api/webhooks/shop/redact"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true