# shopify.app.toml
scopes = "read_orders,read_products,write_products,read_script_tags,write_script_tags,write_draft_orders"
application_url = "https://apps.krcustomizer.com"
embedded = true

[webhooks]
api_version = "2024-10"

# For orders webhook (your business functionality)
[[webhooks.subscriptions]]
topic = "orders/create"
uri = "https://apps.krcustomizer.com/api/webhooks/orders"

# For mandatory GDPR compliance webhooks
[[webhooks.subscriptions]]
topic = "customers/data_request"
uri = "https://apps.krcustomizer.com/api/webhooks/customers/data_request"

[[webhooks.subscriptions]]
topic = "customers/redact" 
uri = "https://apps.krcustomizer.com/api/webhooks/customers/redact"

[[webhooks.subscriptions]]
topic = "shop/redact"
uri = "https://apps.krcustomizer.com/api/webhooks/shop/redact"

[auth]
redirect_urls = [
  "https://apps.krcustomizer.com/api/auth/callback"
]